apiVersion: batch/v1
kind: Job
metadata:
  name: fake-person-worker
spec:
  parallelism: 100
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fake-person-worker
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100M"
              cpu: "0.05"
            limits:
              memory: "200M"
              cpu: "0.1"
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: worker-app-config
                  key: mongo-host
            - name: MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  name: worker-app-config
                  key: mongodb-ml-test-db-user
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: worker-app-secret
                  key: mongodb-ml-test-db-pass










