apiVersion: batch/v1
kind: Job
metadata:
  name: fake-person-worker
  namespace: development
spec:
  parallelism: 1000
  template:
    metadata:
      labels:
        app: fake-person-worker
    spec:
      nodeSelector:
        dedicated: spot
      restartPolicy: OnFailure
      containers:
        - name: fake-person-worker
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100M"
              cpu: "0.1"
            limits:
              memory: "250M"
              cpu: "0.25"
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongo-host
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongodb-root-password
