
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-fake-data-deployment
  labels:
    app: golang-fake-data
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-fake-data
  template:
    metadata:
      labels:
        app: golang-fake-data
    spec:
      nodeSelector:
        dedicated: spot
      schedulerName: volcano
      containers:
        - name: golang-fake-data
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100M"
              cpu: "0.05"
            limits:
              memory: "200M"
              cpu: "0.1"
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: test-app-config
                  key: kafka-host
---



