package fakePersonStruct

type Person struct {
	Id                                                          string
	Name                                                        string
	Gender                                                      string
	Address                                                     string
	Country                                                     string
	City                                                        string
	Continent                                                   string
	Region                                                      string
	Age                                                         int64
	Married                                                     bool
	Phone                                                       string
	CreditCardNumber                                            string
	CreditCardExpirationDateString                              string
	CreditCardType                                              string
	TotalSpendingGold                                           float64
	TotalSessionDuration                                        float64
	StartingDate                                                int64
	CurrentDate                                                 int64
	StartingMonth                                               int64
	CurrentMonth                                                int64
	TotalClickEvent                                             int64
	TotalSessionCount                                           int64
	TotalScore                                                  float64
	TotalGold                                                   int64
	TotalSkillCount                                             int64
	SwipeRightCount                                             int64
	SwipeLeftCount                                              int64
	SwipeDownCount                                              int64
	SwipeUpCount                                                int64
	StartCor                                                    float64
	FinishCor                                                   float64
	RemainLife                                                  float64
	AdvType                                                     string
	ProductType                                                 string
	DeviceType                                                  int64
	GraphicsDeviceType                                          int64
	GraphicsMemorySize                                          int64
	OperatingSystem                                             int64
	ProcessorCount                                              int64
	ProcessorType                                               int64
	SystemMemorySize                                            int64
	FirstSessionYearOfDay                                       int64
	FirstSessionYear                                            int64
	FirstSessionWeekDay                                         int64
	FirstSessionHour                                            int64
	FirstSessionDuration                                        int64
	FirstSessionMinute                                          int64
	SecondSessionHour                                           int64
	SecondSessionDuration                                       int64
	SecondSessionMinute                                         int64
	ThirdSessionHour                                            int64
	ThirdSessionDuration                                        int64
	ThirdSessinMinute                                           int64
	FourthSessionHour                                           int64
	FourthSessionDuration                                       int64
	FourthSessinMinute                                          int64
	FifthSessionHour                                            int64
	FifthSessionDuration                                        int64
	FifthSessinMinute                                           int64
	PenultimateSessionHour                                      int64
	PenultimateSessionDuration                                  int64
	PenultimateSessionMinute                                    int64
	LastSessionYearOfDay                                        int64
	LastSessionYear                                             int64
	LastSessionHour                                             int64
	LastSessionDuration                                         int64
	LastSessionMinute                                           int64
	FirstHalfHourTotalSessionCount                              int64
	FirstHalfHourTotalSessionDuration                           int64
	FirstHourTotalSessionCount                                  int64
	FirstHourTotalSessionDuration                               int64
	FirstTwoHourTotalSessionCount                               int64
	FirstTwoHourTotalSessionDuration                            int64
	FirstThreeHourTotalSessionCount                             int64
	FirstThreeHourTotalSessionDuration                          int64
	FirstSixHourTotalSessionCount                               int64
	FirstSixHourTotalSessionDuration                            int64
	FirstTwelveHourTotalSessionCount                            int64
	FirstTwelveHourTotalSessionDuration                         int64
	TotalSessionDay                                             int64
	TotalSessionHour                                            int64
	TotalSessionMinute                                          int64
	FirstDayTotalSessionCount                                   int64
	FirstDayTotalSessionDuration                                int64
	SecondDayTotalSessionCount                                  int64
	SecondDayTotalSessionDuration                               int64
	ThirdDayTotalSessionCount                                   int64
	ThirdDayTotalSessionDuration                                int64
	FourthDayTotalSessionCount                                  int64
	FourthDayTotalSessionDuration                               int64
	FifthDayTotalSessionCount                                   int64
	FifthDayTotalSessionDuration                                int64
	SixthDayTotalSessionCount                                   int64
	SixthDayTotalSessionDuration                                int64
	SeventhDayTotalSessionCount                                 int64
	SeventhDayTotalSessionDuration                              int64
	MinSessionDuration                                          int64
	MaxSessionDuration                                          int64
	DailyAvegareSessionCount                                    float64
	DailyAverageSessionDuration                                 float64
	SessionBasedAvegareSessionDuration                          float64
	DailyAvegareSessionCountMinusFirstDaySessionCount           float64
	DailyAvegareSessionDurationMinusFirstDaySessionDuration     float64
	SessionBasedAvegareSessionDurationMinusFirstSessionDuration float64
	SessionBasedAvegareSessionDurationMinusLastSessionDuration  float64
	SundaySessionCount                                          int64
	MondaySessionCount                                          int64
	TuesdaySessionCount                                         int64
	WednesdaySessionCount                                       int64
	ThursdaySessionCount                                        int64
	FridaySessionCount                                          int64
	SaturdaySessionCount                                        int64
	AmSessionCount                                              int64
	PmSessionCount                                              int64
	Session0To5HourCount                                        int64
	Session6To11HourCount                                       int64
	Session12To17HourCount                                      int64
	Session18To23HourCount                                      int64
}
